Repository ultralytics/xview-yolov3, pull requests merged in 2025-01, with the labels that each got.

#69 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
Labels: enhancement, devops

#70 Standardize license headers in Python files
  detect.py
  models.py
  scoring/evaluation.py
  scoring/matching.py
  scoring/rectangle.py
  scoring/score.py
  train.py
  utils/__init__.py
  utils/datasets.py
  utils/utils.py
  utils/utils_xview.py
Labels: documentation

#71 Standardize license headers in TOML/YAML files
  .github/dependabot.yml
  .github/workflows/format.yml
  .github/workflows/stale.yml
Labels: documentation, dependencies
